global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'lokoc2623@gmail.com'
        from: 'juliekivuva@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'juliekivuva@gmail.com'
        auth_password: 'novf cehg cqcu pepc'
        require_tls: true



