version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - prometheus
    env_file:
      - ./.env

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    env_file:
      - ./.env

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - "8080:8080"


  ehr-app:
    build: ./ehr-app
    ports:
      - 8081:8081
    depends_on:
      - prometheus
      - grafana
      - alertmanager

  stress_cpu:
    image: polinux/stress
    # command: ["stress", "--cpu", "4", "--timeout", "120s"]
    command: ["sh", "-c", "while true; do stress --cpu 4 --timeout 60s; sleep 120s; done"]
    depends_on:
      - ehr-app


  stress_memory:
    image: polinux/stress
    # command: ["stress", "--vm", "2", "--vm-bytes", "256M", "--timeout", "120s"]
    command: ["sh", "-c", "while true; do stress --vm 2 --vm-bytes 256M --timeout 60s; sleep 120s; done"]
    depends_on:
      - ehr-app

  stress_io:
    image: polinux/stress
    # command: ["stress", "--hdd", "2", "--timeout", "120s"]
    command: ["sh", "-c", "while true; do stress --hdd 2 --timeout 60s; sleep 120s; done"]
    depends_on:
      - ehr-app
